name: Android Build and Deploy

on:
  push:
    branches:
      - main  # Ana dal adınıza göre ayarlayın

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 'Set up latest Oracle JDK 21'
      uses: oracle-actions/setup-java@v1
      with:
        website: oracle.com
        release: 21

    - name: Set up Gradle
      run: |
        chmod +x gradlew
      shell: bash

    - name: Build Android project
      run: ./gradlew build

    - name: Upload APK to GitHub Releases
      id: upload-apk
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/debug/app-debug.apk  # APK dosyasının yolunu ayarlayın
        asset_name: app-debug.apk

    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      with:
        files: app/build/outputs/apk/debug/app-debug.apk  # APK dosyasının yolunu tekrar ayarlayın
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
